services:
  app:
    image: jumdo12/server:gomok
    container_name: gomok-server
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - TZ=Asia/Seoul
      - LOGGING_FILE_NAME=/app/logs/application.log
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  app_logs:
