services:
  app:
    image: jumdo12/server:gomok
    container_name: gomok-server
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
