spring:
  datasource:
    url: ${db.prod.url}
    username: ${db.prod.username}
    password: ${db.prod.password}
    driver-class-name: ${db.prod.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
