spring:
  datasource:
    url: ${db.prod.url}
    username: ${db.prod.username}
    password: ${db.prod.password}
    driver-class-name: ${db.prod.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
